### ISSUE TITLE
Improve config file handling

### ISSUE THREAD

**Issue by phwissmann** [SwissOpenEM/LS_Metadata_reader#2]
A couple of things that could/should be improved:
**Must have:**
- Replace `https://github.com/SwissOpenEM/LS_Metadata_reader/blob/main/configuration/setgetconfig.go#L20` with `os.UserConfigDir()` which is platform independent

**Nice to have:**
- Using viper to parse configs, seehttps://github.com/spf13/viper and in the ingestor https://github.com/SwissOpenEM/Ingestor/blob/main/internal/core/config.go#L40

**Comment by ytittes** [comment]
Hey, good point! I have changed the config overall to now allow flags as an alternative and incorporated os.UserConfigDir()

About the viper part I have not yet implemented that, might do that depending on how the interface will finally look like.
